openapi: 3.2.0
info:
  title: Value Proposition Features API
  version: 0.1.0
tags:
- name: Features
paths:
  /v1/value-proposition/features:
    get:
      tags:
      - Features
      summary: Get the features by account id
      description: Endpoint for reading the feature by account id
      operationId: get_baseline_types_v1_value_proposition_features_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - HTTPBearer: []
components:
  securitySchemes:
    HTTPBearer:
      type: http
      description: Access token in the form of a JWT
      scheme: bearer
